[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]]
repo = 'Shougo/vimproc.vim'
build = 'make'

[[plugins]]
repo = 'Shougo/unite.vim'

[[plugins]]
repo = 'itchyny/lightline.vim'
hook_add = '''
  set laststatus=2
  let g:lightline = {
    \   'colorscheme': 'wombat',
    \   'component': {
    \     'readonly': '%{&readonly?"READ ONLY":""}'
    \   }
    \ }
  if !has('gui_running')
    set t_Co=256
  endif
'''

[[plugins]]
repo = 'derekwyatt/vim-scala'

[[plugins]]
repo = 'vim-ruby/vim-ruby'

[[plugins]]
repo = 'mattn/emmet-vim'

[[plugins]]
repo = 'kchmck/vim-coffee-script'

[[plugins]]
repo = 'groenewege/vim-less'

[[plugins]]
repo = 'plasticboy/vim-markdown'
